#!/usr/bin/env bash
# Back the DCs' LDAPS/TLS with the edy-proxy-go CA (goal 2026-09-01).
#
# Replaces samba's "temporary autogenerated" per-DC self-signed certs with
# leaves issued by the EDY Proxy Root CA — the CA every lab container
# already trusts in its OS store (40-agent.sh put it there). After this,
# any lab client verifies LDAPS against its normal system trust:
#
#     openssl s_client -connect dcN:636 -CAfile /etc/ssl/certs/ca-certificates.crt
#
# Mechanics, all load-bearing:
#   - The "domain-controller" template comes from pki-templates.json — the
#     lab's AD-CS-style template layer over edy's fixed signing profiles.
#   - The private key is generated INSIDE each DC and never leaves it; only
#     the CSR travels. POST /api/certificates (mode=csr) copies the CSR's
#     DNS/IP SANs verbatim into the issued cert; profile=machine gives
#     ServerAuth+ClientAuth for 365 days.
#   - The EDY root is pathlen:0, so it signs leaves only — a subordinate
#     "AD Lab Issuing CA" is not possible until the controller's root is
#     rotated with a longer path length (documented in pki-templates.json).
#   - samba reads the TLS material at START: each DC gets a podman restart
#     (state persists; the entrypoint re-provisions nothing). Agents on the
#     current containers do not survive restarts, so 40-agent.sh runs last.
#   - Idempotent: a DC whose cert is already EDY-issued, SAN-correct, and
#     >30 days from expiry is skipped. --check verifies without changing.
set -euo pipefail
cd "$(dirname "$(readlink -f "$0")")"
. ./agent.env          # lab.env + rdp.env + _edy_admin_curl/EDY_ADMIN_API
[[ $EUID -eq 0 ]] || { echo "run as root"; exit 1; }

CHECK_ONLY=no
[[ "${1:-}" == "--check" ]] && CHECK_ONLY=yes

TLS_DIR=/var/lib/samba/private/tls
TPL=pki-templates.json

# Expand a field of the domain-controller template for one DC.
tpl_field() {   # $1=field $2=fqdn $3=host $4=ip $5=domain
    python3 - "$1" "$2" "$3" "$4" "$5" <<'PY'
import json, sys
f, fqdn, host, ip, domain = sys.argv[1:6]
t = json.load(open("pki-templates.json"))["templates"]["domain-controller"]
print(str(t[f]).replace("{fqdn}", fqdn).replace("{host}", host)
      .replace("{ip}", ip).replace("{domain}", domain))
PY
}

wait_for_dc() {   # $1=ip $2=name — same probe 20-up.sh uses
    local t
    for t in $(seq 1 60); do
        podman exec "$2" samba-tool domain info "$1" >/dev/null 2>&1 && return 0
        sleep 2
    done
    return 1
}

issued=0; skipped=0; failed=0
for i in $(seq 1 "$DC_COUNT"); do
    d=$(dc_name "$i"); ip=$(dc_ip "$i"); fqdn="$d.$DOMAIN_DNS"
    echo "== $d ($fqdn, $ip) =="

    # current cert state, judged in-container
    state=$(podman exec "$d" bash -c "
        openssl x509 -in $TLS_DIR/cert.pem -noout -issuer -checkend 2592000 >/dev/null 2>&1 || { echo need; exit 0; }
        iss=\$(openssl x509 -in $TLS_DIR/cert.pem -noout -issuer)
        san=\$(openssl x509 -in $TLS_DIR/cert.pem -noout -ext subjectAltName 2>/dev/null)
        case \"\$iss\" in *'EDY Proxy Root CA'*) ;; *) echo need; exit 0;; esac
        case \"\$san\" in *$fqdn*) echo ok;; *) echo need;; esac" 2>/dev/null)
    if [[ "$state" == "ok" ]]; then
        echo "  cert already EDY-issued, SAN-correct, >30d left — skipping"
        skipped=$((skipped+1)); continue
    fi
    if [[ "$CHECK_ONLY" == "yes" ]]; then
        echo "  NEEDS ISSUANCE (--check: not changing)"; failed=$((failed+1)); continue
    fi

    subject=$(tpl_field subject "$fqdn" "$d" "$ip" "$DOMAIN_DNS")
    sans=$(tpl_field sans "$fqdn" "$d" "$ip" "$DOMAIN_DNS")
    keyspec=$(tpl_field key "$fqdn" "$d" "$ip" "$DOMAIN_DNS")

    # 1. key + CSR inside the DC; the key never leaves the container
    podman exec "$d" bash -c "
        umask 077
        openssl req -new -newkey $keyspec -nodes \
            -keyout $TLS_DIR/key.edy.pem -out /tmp/$d.csr \
            -subj '$subject' -addext 'subjectAltName=$sans'" \
        || { echo "  CSR generation FAILED"; failed=$((failed+1)); continue; }

    # 2. sign via the controller (primary CA = EDY Proxy Root CA). The JSON
    #    body goes through a file: _edy_admin_curl's stdin already carries
    #    the credential config (-K -), so the body cannot share it.
    csrf=$(mktemp); body=$(mktemp)
    podman exec "$d" cat "/tmp/$d.csr" > "$csrf"
    python3 -c 'import json,sys; print(json.dumps({"mode":"csr","csr_pem":open(sys.argv[1]).read(),"name":sys.argv[2]+"-ldaps","profile":"machine"}))' \
        "$csrf" "$d" > "$body"
    resp=$(_edy_admin_curl -X POST "$EDY_ADMIN_API/api/certificates" \
               -H 'Content-Type: application/json' -d "@$body")
    rm -f "$csrf" "$body"
    cert=$(printf '%s' "$resp" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("certificate_pem",""))' 2>/dev/null)
    chain=$(printf '%s' "$resp" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("chain_pem") or d.get("ca_pem") or "")' 2>/dev/null)
    if [[ -z "$cert" ]]; then
        echo "  ISSUANCE FAILED: $(printf '%s' "$resp" | head -c 200)"
        podman exec "$d" rm -f "$TLS_DIR/key.edy.pem" "/tmp/$d.csr"
        failed=$((failed+1)); continue
    fi

    # 3. install: back up samba's originals once, then swap in the new set
    printf '%s' "$cert"  | podman exec -i "$d" bash -c "cat > $TLS_DIR/cert.edy.pem"
    printf '%s' "$chain" | podman exec -i "$d" bash -c "cat > $TLS_DIR/ca.edy.pem"
    podman exec "$d" bash -c "
        cd $TLS_DIR
        for f in cert key ca; do
            [ -f \$f.samba-orig.pem ] || cp -p \$f.pem \$f.samba-orig.pem
        done
        mv cert.edy.pem cert.pem
        mv ca.edy.pem   ca.pem
        mv key.edy.pem  key.pem
        chmod 600 key.pem; chmod 644 cert.pem ca.pem
        rm -f /tmp/$d.csr"
    echo "  installed EDY-issued cert; restarting samba"

    # 4. samba only reads TLS material at start
    podman restart "$d" >/dev/null
    if wait_for_dc "$ip" "$d"; then
        echo "  $d back, directory serving"
        issued=$((issued+1))
    else
        echo "  $d DID NOT COME BACK — investigate before continuing"; exit 1
    fi
done

if [[ "$CHECK_ONLY" == "no" && $issued -gt 0 ]]; then
    echo "== agents (restarts wiped them on pre-hook containers) =="
    ./40-agent.sh >/dev/null 2>&1 && echo "  40-agent.sh re-applied" || echo "  WARN: 40-agent.sh failed"
fi

echo "== verification: LDAPS chain against the SYSTEM trust store, from a client =="
PASS=0; FAIL=0
for i in $(seq 1 "$DC_COUNT"); do
    d=$(dc_name "$i"); ip=$(dc_ip "$i"); fqdn="$d.$DOMAIN_DNS"
    out=$(podman exec client1 bash -c \
        "echo | timeout 8 openssl s_client -connect $ip:636 \
             -CAfile /etc/ssl/certs/ca-certificates.crt -verify_hostname $fqdn 2>/dev/null \
         | grep -E 'Verify return code'")
    if [[ "$out" == *"Verify return code: 0"* ]]; then
        echo "  PASS  $d LDAPS verifies via system trust (hostname $fqdn)"; PASS=$((PASS+1))
    else
        echo "  FAIL  $d ($out)"; FAIL=$((FAIL+1))
    fi
done
echo "issued=$issued skipped=$skipped failed=$failed | verify: $PASS/$DC_COUNT"
[[ $FAIL -eq 0 && $failed -eq 0 ]]
