// E2E for the DEPLOYED cockpit-adlab plugin (/usr/share/cockpit/adlab):
// every tab renders live domain data with a clean console, and the
// schema-driven modal path is exercised end-to-end with a real user
// create -> verify -> delete against the lab domain.
//
// Runs as cpadmin (NOPASSWD sudo): the adlab helper needs Cockpit's
// superuser bridge, so login() elevates the session first. Password comes
// from the session scratchpad, generated by the cpadmin-setup job.
const { test, expect } = require('@playwright/test');
const fs = require('fs');

const USER = 'cpadmin';
const PASS = fs.readFileSync(
    '/tmp/claude-1000/-home-eddie-Documents-ClaudeSystem/58fcb7e7-7b88-4060-9e49-748c304dc3bf/scratchpad/cpadmin.pass',
    'utf8').trim();
const FRAME = 'iframe[name="cockpit1:localhost/adlab"]';
const QA_USER = 'qa-adlab-user';

// Cockpit's shell emits a transient 401 during the login + superuser-elevation
// + reload handshake (the session probe before the bridge is authenticated).
// It is the shell's, not the plugin's — so we both filter it and, below, only
// start listening for console errors AFTER login() returns.
const IGNORE = [/favicon/i, /vendor\/mermaid/i,
                /401 \(Authentication failed\)/i];

// Attach an error collector and return it. Call AFTER login so the shell's
// login-time handshake noise is not attributed to the plugin.
function watchConsole(page) {
    const errors = [];
    page.on('console', (m) => {
        if (m.type() === 'error' && !IGNORE.some((re) => re.test(m.text())))
            errors.push(m.text());
    });
    return errors;
}

// Elevate the Cockpit session to administrative. cpadmin has NOPASSWD sudo,
// so clicking "Limited access" completes instantly and Cockpit shows a
// success dialog ("You now have administrative access") whose only control
// is Close — there is no password step on this path. Drive it by ROLE so
// PatternFly class-name churn between releases can't break it; tolerate the
// password path too. Idempotent and best-effort: if the toggle isn't shown
// the session is already elevated.
async function elevate(page) {
    const limited = page.getByRole('button', { name: /limited access/i });
    if (!(await limited.isVisible().catch(() => false))) return;
    await limited.click();
    const dlg = page.getByRole('dialog');
    await dlg.waitFor({ state: 'visible', timeout: 15000 }).catch(() => {});
    const pw = dlg.locator('input[type="password"]');
    if (await pw.isVisible().catch(() => false)) {
        await pw.fill(PASS);
        await dlg.getByRole('button', { name: /authenticate|log ?in/i })
            .first().click().catch(() => {});
    }
    const close = dlg.getByRole('button', { name: /^close$/i });
    if (await close.isVisible().catch(() => false)) await close.click().catch(() => {});
    await page.getByText(/administrative access/i).first()
        .waitFor({ state: 'visible', timeout: 20000 }).catch(() => {});
}

async function login(page) {
    await page.goto('/adlab');
    await expect(page.locator('#login-user-input')).toBeVisible({ timeout: 15000 });
    await page.fill('#login-user-input', USER);
    await page.fill('#login-password-input', PASS);
    await page.click('#login-button');
    await page.waitForSelector(FRAME, { state: 'attached', timeout: 45000 });
    await elevate(page);
    // The plugin's boot() may have run before elevation and shown its
    // "helper could not be reached" banner; reload so it re-runs against the
    // now-elevated bridge.
    await page.reload();
    await page.waitForSelector(FRAME, { state: 'attached', timeout: 45000 });
}

async function frame(page) {
    await page.waitForSelector(FRAME, { state: 'attached', timeout: 45000 });
    return page.frameLocator(FRAME);
}

test('plugin loads: domain identity, overview data, clean console', async ({ page }) => {
    test.setTimeout(120000);
    await login(page);
    const errors = watchConsole(page);
    const f = await frame(page);
    await expect(f.locator('#al-identity')).toContainText('AD.EDT1.LAB', { timeout: 45000 });
    // overview cards fill asynchronously; FSMO + containers prove helper I/O
    await expect(f.locator('#al-content')).toContainText('PdcEmulation', { timeout: 60000 });
    await expect(f.locator('#al-content')).toContainText('dc5', { timeout: 30000 });
    await expect(f.locator('#al-content')).toContainText('client10', { timeout: 30000 });
    expect(errors, errors.join(' | ')).toEqual([]);
});

test('every tab renders live data with no visible error banner', async ({ page }) => {
    test.setTimeout(180000);
    await login(page);
    const errors = watchConsole(page);
    const f = await frame(page);
    await expect(f.locator('#al-identity')).toContainText('AD.EDT1.LAB', { timeout: 45000 });

    const TABS = [
        ['Users & Computers', 'Administrator'],   // dsa.msc console: the well-known account
        ['Group Policy', 'Default Domain Policy'],  // gpmc.msc: default GPO
        ['Sites & Replication', 'Default-First-Site-Name'],
        ['DNS', 'ad.edt1.lab'],
        ['Domain Controllers', 'dc1'],
        ['Clients', 'client10'],
        ['Activity', 'adlab-admin'],
    ];
    for (const [label, marker] of TABS) {
        await f.locator('#al-tabs button', { hasText: label }).click();
        await expect(f.locator('#al-content')).toContainText(marker, { timeout: 45000 });
        const bad = await f.locator('#al-content .al-alert.err').evaluateAll(
            (els) => els.filter((e) => e.offsetParent !== null &&
                                       e.textContent.trim()).map((e) => e.textContent.trim()));
        expect(bad, `${label}: ${bad.join(' | ')}`).toEqual([]);
    }
    expect(errors, errors.join(' | ')).toEqual([]);
});

// RETIRED TAB: this test drove the 'Users & Groups' tab's .al-actions bar, which
// was removed when #/users was retired in favour of the objects console (#/objects).
// The equivalent flow there is the container tree's context menu (New > user), a
// different interaction entirely -- not a selector swap. Skipped rather than
// silently deleted so the lost coverage stays visible. Rewriting it needs a run
// against live Cockpit to confirm the menu selectors.
test.skip('schema-driven modals: create user, see one-time password, delete with typed confirm', async ({ page }) => {
    test.setTimeout(180000);
    await login(page);
    const f = await frame(page);
    await expect(f.locator('#al-identity')).toContainText('AD.EDT1.LAB', { timeout: 45000 });
    await f.locator('#al-tabs button', { hasText: 'Users & Groups' }).click();
    await expect(f.locator('#al-content')).toContainText('Administrator', { timeout: 45000 });

    // create — the form is rendered from the helper's own schema
    await f.locator('.al-actions button', { hasText: 'Create user' }).first().click();
    await f.locator('.al-modal input[name="name"]').fill(QA_USER);
    await f.locator('.al-modal button[type="submit"]').click();
    // result modal shows the generated password exactly once
    await expect(f.locator('.al-modal .al-alert.warn')).toContainText('Generated password',
        { timeout: 60000 });
    const shown = await f.locator('.al-modal kbd.al').textContent();
    expect(shown.length).toBeGreaterThan(12);
    await f.locator('.al-modal button', { hasText: 'Close' }).click();

    // the users table refreshes and carries the new account
    await f.locator('.al-card input[type="search"]').fill(QA_USER);
    await expect(f.locator('#al-content')).toContainText(QA_USER, { timeout: 60000 });

    // delete — danger verb demands the typed verb name
    await f.locator('table.al tr', { hasText: QA_USER })
        .locator('button', { hasText: 'delete' }).click();
    const confirmBox = f.locator('.al-modal input[type="text"]').last();
    await confirmBox.fill('user-delete');
    await f.locator('.al-modal button[type="submit"]').click();
    await expect(f.locator('.al-modal')).toContainText('"deleted"', { timeout: 60000 });
    await f.locator('.al-modal button', { hasText: 'Close' }).click();
});
